### ISSUE TITLE
Misleading definition in VTK_UnstructuredGrid of Class_VTK.

### ISSUE THREAD

**Issue by roccoarpa** [optimad/opt_IO#2]
Ok, here we have a cell field and a connectivity field. In a triangulation for example, n_cells=100 requires n_conn = 3*100; in Write/ Read routines, Field_C for connectivity is defined  as a vector2D of n_cells as primary dimension and local dimension of 1. This is incongruent with n_conn dimension. 
Two solutions are possible: define connectivity field with local dimension 3, or resize connectivity field to variable n_conn and not n_cells in write/read. The latter solution is far more general than the former one, for mixed type unstructured tassellations.

**Comment by haysam** [comment]
Unfortunately the vtk unstructured grid format does not allow to deduce the size of the "connectivity" vector from the header information. The size of the "connectivity" vector can be determined once the "types" have been read. This is the reason why the connectivity vector is the last to be read during .Read() in order to permit the user to allocate necessary data structures to host the "connectivity" information.
